### ISSUE TITLE
Melhorias CSS

### ISSUE THREAD

**Issue by C0lliNN** [Josuerx12/selfcare#2]
Para tornar o css mais legível, é recomendado colocar uma linha de espaço entre dois blocos. Algo assim:
```css
#button_s {
    text-decoration: none;
    color: #fff;
}

#iconsize {
    height: 28px;
    width: 32px;
    padding: 4px;
}
```
https://github.com/Josuerx12/selfcare/blob/a96f4784b13da6d3ebc3a7ddef6ae168afbb747a/style.css#L42-L50

É importante que você consistente na hora de nomear os ids e classes. Em alguns lugares você está colocando duas palavras juntas sem nenhum divisor e outros você separa as palavras com um '_'. O que eu mais vejo no css, é a gente separar as palavras de um identificador usando '-'. `#lista-final`, `.fo-list`.
https://github.com/Josuerx12/selfcare/blob/a96f4784b13da6d3ebc3a7ddef6ae168afbb747a/style.css#L28

O valor da propriedade gap geralmente é em px, porque usando % o espaçamento pode variar muito de acordo com o tamanho da página.
https://github.com/Josuerx12/selfcare/blob/a96f4784b13da6d3ebc3a7ddef6ae168afbb747a/style.css#L108

No geral, gostei do seu uso de flexbox.
